### PR TITLE
WIP: Upload a report to a configured endpoint

### LINKED ISSUE #33: Support serverless collection of data about executed checks
Right now GatorGrader does not have a feature that will track information about which checks pass and fail across multiple runs. This means that it is very difficult to see patterns about the checks across all of the students in all of the courses for which GatorGrader is in use. 

One idea would be to adopt a serverless approach where a Python function is installed on Amazon. This function could store information in a Dynamo data store in an anonymous fashion. At the start, this function could store either the name or identifier of a check, details about an assignment/course, and a status about whether or not the check passed.

Note that this idea is an advanced feature that moves beyond the standard approach adopted by GatorGrader. However, the complete implementation of this feature would definitely make it easier for instructors who use GatorGrader to learn about how their students are doing in a course.

Finally, this feature requires careful thought about the security implications. By default, GatorGrader should not track this information. If the tracking of this information is enabled, then we need to think carefully about how we store and manage the data so that privacy is preserved. Also, when GatorGrader is adopted by others outside of Allegheny College we will need to further consider the mixture of data from multiple instructors and institutions.

### PR DESCRIPTION
**Pull request by Michionlion**
This PR, while still in development, has all the core features required for sending an HTTP POST request to a specified endpoint whenever `gradle grade` is run. This request has a JSON body as seen below. There are some additional considerations for this PR: the biggest one is how to identify each user, since there may not be a central identification paradigm. We could use the configured Git email (which may be machine based), an IP, a machine hostname, etc. All of these have various drawbacks, and I'd like to open this up for discussion. As well as that, is there any more datapoints we should be collecting?

```json
{
  "user": "example@gmail.com",
  "time": "2019-05-31T13:12:45.248750Z",
  "assignment": "gatorgrader-samplelab",
  "report": {
    "numberOfChecks": 4,
    "numberOfFailures": 2,
    "results": [
      {
        "check": "The reflection.md in writing has at least 6 word(s) in every paragraph",
        "outcome": false,
        "diagnostic": "Found 3 word(s) in a paragraph of the specified file"
      }, {
        "check": "The SampleLabMain.java in src/main/java/samplelab has exactly 2 matches of the 'new\\\\s+\\\\S+?\\\\(.*?\\\\)' regular expression",
        "outcome": true,
        "diagnostic": ""
      }, {
        "check": "The SampleLabMain.java in src/main/java/samplelab has at least 2 of the 'println(' fragment",
        "outcome": true,
        "diagnostic": ""
      }, {
        "check": "The SampleLabMain.java in src/main/java/samplelab has at least 3 multiple-line Java comment(s)",
        "outcome": false,
        "diagnostic": "Found 2 comment(s) in the specified file"
      }
    ]
  }
}
```

This PR is a feature update that fixes #33.

##### Developers
@Michionlion
@enpuyou

### CODE REVIEW

**Review by gkapfham — DISMISSED** [review]
Hi @Michionlion, I approve all of these changes. Some quick questions:
1) Is it possible to document the JSON object's current structure?
2) Can you document how to cut a release of the Gradle plugin?
3) Can you document how the YAML file will allow an instructor to "opt-in" to the monitoring?

Broadly, I would like to see more about how these features will be used in practice. With that said, I trust the quality of the code and the vision that you are developing for this feature. Thanks!

**Comment by gkapfham** [comment]
Hi @Michionlion, is it this PR that will ultimately make it possible to use the `version:` tag correctly? What do we need to fix for this PR so that this tag will start working and then we can more effectively do local testing with a tagged/branched version of GatorGrader?

**Comment by Michionlion** [comment]
No, that fix has not been made yet, although this should work for non-branches and new branches; but if a branch is updated, only a fetch is performed, not a pull. That will change in the future when I get a chance to add that!

**Comment by gkapfham** [comment]
Hi @Michionlion, when you have time, can you please give me a status update on this PR? I plan to start working on the linting interface and the plugin architecture over the weekend and I'm guessing that it would be useful for me to have a fully working version of the `version:` tag so that I can easily try out my implementation in an existing project. Thanks again for your help with this plugin! Any insights and effort that you can provide would be greatly appreciated!

**Comment by Michionlion** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 18
           

Complexity increasing per file
==============================
- src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java  8
- src/main/java/org/gatorgradle/display/CommandOutputSummary.java  2
- src/main/java/org/gatorgradle/task/GatorGradleReportTask.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/org/gatorgradle/task/GatorGradleTask.java  -8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/GatorEducator/gatorgradle/pullRequest?prid=3661039&bid=12932922)

**Review by Michionlion — COMMENTED** [review]
I think the only thing we need to discuss now is the endpoint configuration and security concerns.

**Comment by Michionlion** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 18
           

Complexity increasing per file
==============================
- src/main/java/org/gatorgradle/display/CommandOutputSummary.java  2
- src/main/java/org/gatorgradle/task/GatorGradleReportTask.java  1
- src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java  8
         

Complexity decreasing per file
==============================
+ src/main/java/org/gatorgradle/task/GatorGradleTask.java  -8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/GatorEducator/gatorgradle/pullRequest?prid=3661039&bid=12932922)

**Comment by Michionlion** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 18
           

Complexity increasing per file
==============================
- src/main/java/org/gatorgradle/task/GatorGradleReportTask.java  1
- src/main/java/org/gatorgradle/display/CommandOutputSummary.java  2
- src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java  8
         

Complexity decreasing per file
==============================
+ src/main/java/org/gatorgradle/task/GatorGradleTask.java  -8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/GatorEducator/gatorgradle/pullRequest?prid=3661039&bid=12932922)

**Comment by Michionlion** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 18
           

Complexity increasing per file
==============================
- src/main/java/org/gatorgradle/display/CommandOutputSummary.java  2
- src/main/java/org/gatorgradle/task/GatorGradleReportTask.java  1
- src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java  8
         

Complexity decreasing per file
==============================
+ src/main/java/org/gatorgradle/task/GatorGradleTask.java  -8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/GatorEducator/gatorgradle/pullRequest?prid=3661039&bid=12932922)

**Comment by Michionlion** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 19
           

Complexity increasing per file
==============================
- src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java  8
- src/main/java/org/gatorgradle/task/GatorGradleReportTask.java  1
- src/main/java/org/gatorgradle/display/CommandOutputSummary.java  2
         

Complexity decreasing per file
==============================
+ src/main/java/org/gatorgradle/task/GatorGradleTask.java  -8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/GatorEducator/gatorgradle/pullRequest?prid=3661039&bid=12932922)

**Comment by Michionlion** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 19
           

Complexity increasing per file
==============================
- src/main/java/org/gatorgradle/display/CommandOutputSummary.java  2
- src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java  8
- src/main/java/org/gatorgradle/task/GatorGradleReportTask.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/org/gatorgradle/task/GatorGradleTask.java  -8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/GatorEducator/gatorgradle/pullRequest?prid=3661039&bid=12932922)

**Comment by Michionlion** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 10
           

Complexity increasing per file
==============================
- src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java  8
- src/main/java/org/gatorgradle/task/GatorGradleReportTask.java  1
- src/main/java/org/gatorgradle/display/CommandOutputSummary.java  2
         

Complexity decreasing per file
==============================
+ src/main/java/org/gatorgradle/task/GatorGradleTask.java  -8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/GatorEducator/gatorgradle/pullRequest?prid=3661039&bid=12932922)

**Comment by Michionlion** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 15
- Added 10
           

Complexity increasing per file
==============================
- src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java  8
- src/main/java/org/gatorgradle/display/CommandOutputSummary.java  2
- src/main/java/org/gatorgradle/task/GatorGradleReportTask.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/org/gatorgradle/task/GatorGradleTask.java  -8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/GatorEducator/gatorgradle/pullRequest?prid=3661039&bid=12932922)

**Comment by Michionlion** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 33
- Added 10
           

Complexity increasing per file
==============================
- src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java  8
- src/main/java/org/gatorgradle/task/GatorGradleReportTask.java  1
- src/main/java/org/gatorgradle/display/CommandOutputSummary.java  2
         

Complexity decreasing per file
==============================
+ src/main/java/org/gatorgradle/task/GatorGradleTask.java  -8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/GatorEducator/gatorgradle/pullRequest?prid=3661039&bid=12932922)

**Comment by Michionlion** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 33
- Added 10
           

Complexity increasing per file
==============================
- src/main/java/org/gatorgradle/task/GatorGradleReportTask.java  1
- src/main/java/org/gatorgradle/display/CommandOutputSummary.java  2
- src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java  8
         

Complexity decreasing per file
==============================
+ src/main/java/org/gatorgradle/task/GatorGradleTask.java  -8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/GatorEducator/gatorgradle/pullRequest?prid=3661039&bid=12932922)

**Review by enpuyou — APPROVED** [review]

**Comment by Michionlion** [comment]
Are we ready for merging here? Does the configuration setup now implemented work for our needs?

**Comment by Michionlion** [comment]
I would like at least one independent code review of everything one more time before we merge it, @gkapfham @schultzh @corlettim @alexheinle.

**Review by corlettim — APPROVED** [review]

**Comment by Michionlion** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 33
- Added 10
           

Complexity increasing per file
==============================
- src/main/java/org/gatorgradle/display/CommandOutputSummary.java  2
- src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java  8
- src/main/java/org/gatorgradle/task/GatorGradleReportTask.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/org/gatorgradle/task/GatorGradleTask.java  -8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/GatorEducator/gatorgradle/pullRequest?prid=3661039&bid=12932922)

**Comment by enpuyou** [comment]
> Are we ready for merging here? Does the configuration setup now implemented work for our needs?

Yes @Michionlion since we have decided to use plaintext, the code we have now should work. I have also added some documentation/instruction to the README. After merging this PR, I will test it again in Travis CI.

**Pull request merged**
